# Generated by Django 5.2.7 on 2026-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="radar_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
