# Generated by Django 5.2.7 on 2026-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_interviewhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="ats_keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="skill_gap",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
