# Generated by Django 5.2.7 on 2026-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_analysishistory_ats_keywords_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysishistory",
            old_name="skill_gap",
            new_name="skill_gaps",
        ),
    ]
