# Generated by Django 5.2.5 on 2026-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysishistory",
            name="breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="file_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="issues",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysishistory",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
