# Generated by Django 5.2.5 on 2026-04-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_userprofile_achievements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("points", models.IntegerField(default=10)),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Hàng ngày"),
                            ("ONE_TIME", "Một lần"),
                            ("ACHIEVEMENT", "Thành tựu"),
                        ],
                        default="ONE_TIME",
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(default="Sparkles", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("is_claimed", models.BooleanField(default=False)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quest"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "quest")},
            },
        ),
    ]
