# Generated by Django 5.2.5 on 2026-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_quest_userprofile_last_login_date_userquest"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysishistory",
            name="career_intelligence",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="personalized_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="recruiter_brain",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysishistory",
            name="truth_detection",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
